apiVersion: v1
kind: Service
metadata:
  name: blue
spec:
  ports:
    - name: http1
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: blue
  sessionAffinity: None
  type: LoadBalancer
